-- GENERATED from migrations/ by scripts/migrate.py --dialect snowflake. Do not edit.
-- Running this file creates the tables. `migrate.apply` (the service at startup,
-- or this script without --dry-run) runs the same statements and additionally
-- records each version in schema_migrations; both paths are idempotent.

CREATE DATABASE IF NOT EXISTS MEMORYLEDGER;
CREATE SCHEMA IF NOT EXISTS MEMORYLEDGER.LEDGER;
USE SCHEMA MEMORYLEDGER.LEDGER;

CREATE TABLE IF NOT EXISTS SCHEMA_MIGRATIONS (
    VERSION STRING NOT NULL,
    APPLIED_AT STRING NOT NULL,
    PRIMARY KEY (VERSION)
);

-- 0001_initial
CREATE TABLE IF NOT EXISTS CALL_LOG (
    CALL_ID STRING NOT NULL,
    SESSION_ID STRING NOT NULL,
    USER_ID STRING NOT NULL,
    TS TIMESTAMP_NTZ NOT NULL,
    MODE STRING NOT NULL,
    MODEL STRING,
    INPUT_TOKENS NUMBER NOT NULL,
    OUTPUT_TOKENS NUMBER NOT NULL,
    CACHED_TOKENS NUMBER NOT NULL,
    CACHE_WRITE_TOKENS NUMBER NOT NULL,
    COST_USD FLOAT NOT NULL,
    COST_UNCACHED_USD FLOAT NOT NULL,
    COST_CACHED_USD FLOAT NOT NULL,
    COST_WRITE_USD FLOAT NOT NULL,
    COST_OUTPUT_USD FLOAT NOT NULL,
    LATENCY_MS FLOAT,
    BREAKPOINT_COUNT NUMBER,
    TIER_TOKENS STRING,
    BASELINE_COST_USD FLOAT NOT NULL,
    PRIMARY KEY (CALL_ID)
);

CREATE TABLE IF NOT EXISTS MEMORY_INJECTIONS (
    CALL_ID STRING NOT NULL,
    MEMORY_ID STRING NOT NULL,
    USER_ID STRING NOT NULL,
    TS TIMESTAMP_NTZ NOT NULL,
    TIER NUMBER NOT NULL,
    MEMORY_TYPE STRING NOT NULL,
    TOKENS NUMBER NOT NULL,
    WAS_CACHED BOOLEAN NOT NULL,
    ATTRIBUTED_COST_USD FLOAT NOT NULL,
    PRIMARY KEY (CALL_ID, MEMORY_ID)
);

CREATE TABLE IF NOT EXISTS MEMORY_REGISTRY (
    MEMORY_ID STRING NOT NULL,
    USER_ID STRING NOT NULL,
    MEMORY_TYPE STRING NOT NULL,
    CONTENT_HASH STRING NOT NULL,
    TIER NUMBER NOT NULL,
    STABLE_CALLS NUMBER NOT NULL,
    TOKENS NUMBER NOT NULL,
    FIRST_SEEN TIMESTAMP_NTZ NOT NULL,
    LAST_SEEN TIMESTAMP_NTZ NOT NULL,
    PRIMARY KEY (MEMORY_ID)
);

CREATE TABLE IF NOT EXISTS ABLATION_RESULTS (
    ABLATION_ID STRING NOT NULL,
    MEMORY_ID STRING NOT NULL,
    USER_ID STRING NOT NULL,
    TS TIMESTAMP_NTZ NOT NULL,
    PROMPT STRING,
    BASELINE_ANSWER STRING,
    ABLATED_ANSWER STRING,
    SIMILARITY FLOAT,
    VERDICT STRING,
    TOKENS_SAVED NUMBER,
    MONTHLY_COST_USD FLOAT,
    PRIMARY KEY (ABLATION_ID)
);

-- 0002_lifecycle
CREATE TABLE IF NOT EXISTS MEMORY_LIFECYCLE (
    MEMORY_ID STRING NOT NULL,
    RETIRED_AT TIMESTAMP_NTZ,
    RETIRED_REASON STRING,
    PRIMARY KEY (MEMORY_ID)
);

CREATE TABLE IF NOT EXISTS EPISODE_WRITES (
    USER_ID STRING NOT NULL,
    CONTENT_SHA256 STRING NOT NULL,
    TS TIMESTAMP_NTZ NOT NULL,
    PRIMARY KEY (USER_ID, CONTENT_SHA256)
);

CREATE TABLE IF NOT EXISTS ABLATION_RESULTS (
    ABLATION_ID STRING NOT NULL,
    MEMORY_ID STRING NOT NULL,
    USER_ID STRING NOT NULL,
    TS TIMESTAMP_NTZ NOT NULL,
    PROMPT STRING,
    BASELINE_ANSWER STRING,
    ABLATED_ANSWER STRING,
    SIMILARITY FLOAT,
    VERDICT STRING,
    TOKENS_SAVED NUMBER,
    MONTHLY_COST_USD FLOAT,
    PROBES_TESTED NUMBER,
    PRIMARY KEY (ABLATION_ID)
);
