-- MemoryLedger Snowflake objects. Primary/check constraints are declarative;
-- Snowflake standard tables do not enforce them, so writers must still validate.

CREATE DATABASE IF NOT EXISTS MEMORYLEDGER;
CREATE SCHEMA IF NOT EXISTS MEMORYLEDGER.LEDGER;
USE SCHEMA MEMORYLEDGER.LEDGER;

CREATE TABLE IF NOT EXISTS CALL_LOG (
    CALL_ID STRING PRIMARY KEY,
    SESSION_ID STRING,
    USER_ID STRING,
    TS TIMESTAMP_NTZ,
    MODE STRING,
    MODEL STRING,
    INPUT_TOKENS NUMBER,
    OUTPUT_TOKENS NUMBER,
    CACHED_TOKENS NUMBER,
    CACHE_WRITE_TOKENS NUMBER,
    COST_USD FLOAT,
    COST_UNCACHED_USD FLOAT,
    COST_CACHED_USD FLOAT,
    COST_WRITE_USD FLOAT,
    COST_OUTPUT_USD FLOAT,
    LATENCY_MS FLOAT,
    BREAKPOINT_COUNT NUMBER,
    TIER_TOKENS VARIANT,
    BASELINE_COST_USD FLOAT
)
CLUSTER BY (TO_DATE(TS), USER_ID);

CREATE TABLE IF NOT EXISTS MEMORY_INJECTIONS (
    CALL_ID STRING,
    MEMORY_ID STRING,
    USER_ID STRING,
    TS TIMESTAMP_NTZ,
    TIER NUMBER,
    MEMORY_TYPE STRING,
    TOKENS NUMBER,
    WAS_CACHED BOOLEAN,
    ATTRIBUTED_COST_USD FLOAT
)
CLUSTER BY (TO_DATE(TS), USER_ID);

CREATE TABLE IF NOT EXISTS MEMORY_REGISTRY (
    MEMORY_ID STRING PRIMARY KEY,
    USER_ID STRING,
    MEMORY_TYPE STRING,
    CONTENT_HASH STRING,
    TIER NUMBER,
    STABLE_CALLS NUMBER,
    TOKENS NUMBER,
    FIRST_SEEN TIMESTAMP_NTZ,
    LAST_SEEN TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS ABLATION_RESULTS (
    ABLATION_ID STRING PRIMARY KEY,
    MEMORY_ID STRING,
    USER_ID STRING,
    TS TIMESTAMP_NTZ,
    PROMPT STRING,
    BASELINE_ANSWER STRING,
    ABLATED_ANSWER STRING,
    SIMILARITY FLOAT,
    VERDICT STRING CHECK (VERDICT IN ('evict', 'keep', 'inconclusive')),
    TOKENS_SAVED NUMBER,
    MONTHLY_COST_USD FLOAT
);

