-- Dashboard rollups for the rolling 30-day ledger window.
USE SCHEMA MEMORYLEDGER.LEDGER;

CREATE OR REPLACE VIEW V_MEMORY_MONTHLY_COST AS
WITH WINDOWED AS (
    SELECT *
    FROM MEMORY_INJECTIONS
    WHERE TS >= DATEADD('day', -30, CURRENT_TIMESTAMP())
),
ROLLUP AS (
    SELECT
        MEMORY_ID,
        USER_ID,
        COUNT(*) AS INJECTIONS_30D,
        SUM(TOKENS) AS TOTAL_TOKENS_30D,
        COUNT_IF(WAS_CACHED)::FLOAT / NULLIF(COUNT(*), 0) AS CACHE_HIT_RATE,
        SUM(IFF(WAS_CACHED, TOKENS, 0)) AS CACHED_TOKENS_30D,
        SUM(ATTRIBUTED_COST_USD) AS COST_30D_USD,
        GREATEST(1, DATEDIFF('day', MIN(TS), MAX(TS)) + 1) AS OBSERVED_DAYS
    FROM WINDOWED
    GROUP BY MEMORY_ID, USER_ID
)
SELECT
    MEMORY_ID,
    USER_ID,
    INJECTIONS_30D,
    TOTAL_TOKENS_30D,
    CACHE_HIT_RATE,
    CACHED_TOKENS_30D,
    COST_30D_USD,
    COST_30D_USD * 30.0 / OBSERVED_DAYS AS PROJECTED_MONTHLY_COST_USD
FROM ROLLUP;

CREATE OR REPLACE VIEW V_CACHE_HIT_BY_TIER AS
SELECT
    MI.TIER,
    CL.MODE,
    COUNT(*) AS INJECTIONS_30D,
    SUM(MI.TOKENS) AS TOKEN_VOLUME_30D,
    COUNT_IF(MI.WAS_CACHED)::FLOAT / NULLIF(COUNT(*), 0) AS CACHE_HIT_RATE,
    SUM(IFF(MI.WAS_CACHED, MI.TOKENS, 0))::FLOAT
        / NULLIF(SUM(MI.TOKENS), 0) AS TOKEN_WEIGHTED_CACHE_HIT_RATE
FROM MEMORY_INJECTIONS AS MI
JOIN CALL_LOG AS CL ON CL.CALL_ID = MI.CALL_ID
WHERE MI.TS >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY MI.TIER, CL.MODE;

CREATE OR REPLACE VIEW V_MODE_COMPARISON AS
WITH CALL_STATS AS (
    SELECT
        MODE,
        COUNT(*) AS CALLS_30D,
        AVG(COST_USD) AS MEAN_COST_PER_CALL_USD,
        STDDEV_SAMP(COST_USD) AS STDDEV_COST_PER_CALL_USD,
        AVG(BASELINE_COST_USD) AS MEAN_ZERO_CACHE_BASELINE_PER_CALL_USD,
        AVG(LATENCY_MS) AS MEAN_LATENCY_MS
    FROM CALL_LOG
    WHERE TS >= DATEADD('day', -30, CURRENT_TIMESTAMP())
    GROUP BY MODE
),
CONVERSATION_COSTS AS (
    SELECT
        MODE,
        SESSION_ID,
        SUM(COST_USD) AS CONVERSATION_COST_USD
    FROM CALL_LOG
    WHERE TS >= DATEADD('day', -30, CURRENT_TIMESTAMP())
    GROUP BY MODE, SESSION_ID
),
CONVERSATION_STATS AS (
    SELECT
        MODE,
        COUNT(*) AS CONVERSATIONS_30D,
        AVG(CONVERSATION_COST_USD) AS MEAN_COST_PER_CONVERSATION_USD,
        STDDEV_SAMP(CONVERSATION_COST_USD) AS STDDEV_COST_PER_CONVERSATION_USD
    FROM CONVERSATION_COSTS
    GROUP BY MODE
)
SELECT
    C.MODE,
    C.CALLS_30D,
    S.CONVERSATIONS_30D,
    C.MEAN_COST_PER_CALL_USD,
    C.STDDEV_COST_PER_CALL_USD,
    S.MEAN_COST_PER_CONVERSATION_USD,
    S.STDDEV_COST_PER_CONVERSATION_USD,
    C.MEAN_ZERO_CACHE_BASELINE_PER_CALL_USD,
    C.MEAN_LATENCY_MS
FROM CALL_STATS AS C
JOIN CONVERSATION_STATS AS S USING (MODE);

CREATE OR REPLACE VIEW V_EVICTION_CANDIDATES AS
WITH LATEST_ABLATION AS (
    SELECT
        ABLATION_ID,
        MEMORY_ID,
        USER_ID,
        TS AS ABLATED_AT,
        SIMILARITY,
        VERDICT,
        TOKENS_SAVED,
        MONTHLY_COST_USD AS ABLATION_MONTHLY_COST_USD
    FROM ABLATION_RESULTS
    QUALIFY ROW_NUMBER() OVER (PARTITION BY MEMORY_ID, USER_ID ORDER BY TS DESC) = 1
)
SELECT
    RANK() OVER (ORDER BY C.PROJECTED_MONTHLY_COST_USD DESC) AS COST_RANK,
    C.MEMORY_ID,
    C.USER_ID,
    C.INJECTIONS_30D,
    C.TOTAL_TOKENS_30D,
    C.CACHE_HIT_RATE,
    C.COST_30D_USD,
    C.PROJECTED_MONTHLY_COST_USD,
    A.ABLATION_ID,
    A.ABLATED_AT,
    A.SIMILARITY,
    A.VERDICT,
    A.TOKENS_SAVED,
    A.ABLATION_MONTHLY_COST_USD
FROM V_MEMORY_MONTHLY_COST AS C
JOIN LATEST_ABLATION AS A
    ON A.MEMORY_ID = C.MEMORY_ID AND A.USER_ID = C.USER_ID
WHERE A.VERDICT = 'evict';
