-- POST-HOC CREDIBILITY CHECK ONLY: SNOWFLAKE.ACCOUNT_USAGE can lag by up to
-- 45 minutes, so this reconciliation must never drive the live cost meter.
-- It compares MemoryLedger totals with Snowflake Cortex REST usage by UTC hour.

USE SCHEMA MEMORYLEDGER.LEDGER;

WITH OUR_USAGE AS (
    SELECT
        DATE_TRUNC('hour', TS) AS USAGE_HOUR,
        COUNT(*) AS OUR_CALLS,
        SUM(INPUT_TOKENS) AS OUR_INPUT_TOKENS,
        SUM(OUTPUT_TOKENS) AS OUR_OUTPUT_TOKENS,
        SUM(INPUT_TOKENS + OUTPUT_TOKENS) AS OUR_TOTAL_TOKENS
    FROM CALL_LOG
    WHERE TS >= DATEADD('day', -7, CURRENT_TIMESTAMP())
    GROUP BY 1
),
SNOWFLAKE_USAGE AS (
    SELECT
        -- VERIFY-AT-EVENT: set the session timezone to UTC before this NTZ cast.
        DATE_TRUNC('hour', START_TIME)::TIMESTAMP_NTZ AS USAGE_HOUR,
        COUNT(*) AS SNOWFLAKE_CALLS,
        SUM(TOKENS_GRANULAR:"input"::NUMBER) AS SNOWFLAKE_INPUT_TOKENS,
        -- VERIFY-AT-EVENT: confirm the account emits the documented lowercase object keys.
        SUM(TOKENS_GRANULAR:"output"::NUMBER) AS SNOWFLAKE_OUTPUT_TOKENS,
        SUM(TOKENS) AS SNOWFLAKE_TOTAL_TOKENS
    -- VERIFY-AT-EVENT: requires IMPORTED PRIVILEGES on the SNOWFLAKE database.
    FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_REST_API_USAGE_HISTORY
    WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
    GROUP BY 1
)
SELECT
    COALESCE(O.USAGE_HOUR, S.USAGE_HOUR) AS USAGE_HOUR,
    COALESCE(O.OUR_CALLS, 0) AS OUR_CALLS,
    COALESCE(S.SNOWFLAKE_CALLS, 0) AS SNOWFLAKE_CALLS,
    COALESCE(O.OUR_INPUT_TOKENS, 0) AS OUR_INPUT_TOKENS,
    COALESCE(S.SNOWFLAKE_INPUT_TOKENS, 0) AS SNOWFLAKE_INPUT_TOKENS,
    COALESCE(O.OUR_INPUT_TOKENS, 0) - COALESCE(S.SNOWFLAKE_INPUT_TOKENS, 0)
        AS INPUT_TOKEN_DELTA,
    COALESCE(O.OUR_OUTPUT_TOKENS, 0) AS OUR_OUTPUT_TOKENS,
    COALESCE(S.SNOWFLAKE_OUTPUT_TOKENS, 0) AS SNOWFLAKE_OUTPUT_TOKENS,
    COALESCE(O.OUR_OUTPUT_TOKENS, 0) - COALESCE(S.SNOWFLAKE_OUTPUT_TOKENS, 0)
        AS OUTPUT_TOKEN_DELTA,
    COALESCE(O.OUR_TOTAL_TOKENS, 0) AS OUR_TOTAL_TOKENS,
    COALESCE(S.SNOWFLAKE_TOTAL_TOKENS, 0) AS SNOWFLAKE_TOTAL_TOKENS,
    COALESCE(O.OUR_TOTAL_TOKENS, 0) - COALESCE(S.SNOWFLAKE_TOTAL_TOKENS, 0)
        AS TOTAL_TOKEN_DELTA
FROM OUR_USAGE AS O
FULL OUTER JOIN SNOWFLAKE_USAGE AS S USING (USAGE_HOUR)
ORDER BY USAGE_HOUR DESC;
